### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by n-rodriguez** [bovender/imapcli#5]
Hi there! Is this project still maintained?

Thank you!

**Comment by bovender** [comment]
Hi, well I'm still here :wink:  Although I have extremely little time for my programming hobby :cry: 

Is there anything specific that you need, or do you have a problem that I could try to look into?

I use this little program occasionally to investigate the state of my own IMAP server, works well for me. Actually I prefer to use the Docker image: https://hub.docker.com/r/bovender/imapcli

```
$ docker run -it bovender/imapcli -s [REDACTED] -u [REDACTED] -P info
Enter password: ••••••••
server: [REDACTED]
user: [REDACTED]
greeting: [REDACTED] ready
capability: IMAP4REV1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY SPECIAL-USE
hierarchy separator: /
quota: IMAP QUOTA extension not supported by this server
```

**Comment by n-rodriguez** [comment]
> Is there anything specific that you need, or do you have a problem that I could try to look into?

I'm planning to do a bunch of PRs to keep it alive :) : basically :

- adding GithubActions
- adding net-imap in gemspec (net-imap is now an external gem)
- and maybe more :)

**Comment by bovender** [comment]
Yes please, go ahead, I'm looking forward to your PRs!
